# Generated by Django 5.2.8 on 2025-11-19 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ministries', '0001_initial'),
        ('volunteers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('mass', 'Mass'), ('meeting', 'Meeting'), ('outreach', 'Outreach Program'), ('fundraiser', 'Fundraiser'), ('celebration', 'Celebration'), ('other', 'Other')], default='other', max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=300)),
                ('max_volunteers', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_volunteers', models.ManyToManyField(blank=True, related_name='assigned_events', to='volunteers.volunteer')),
                ('coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_events', to=settings.AUTH_USER_MODEL)),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='ministries.ministry')),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
    ]
