# Generated by Django 5.2.8 on 2025-11-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='supporting_document',
            field=models.FileField(blank=True, help_text='Upload a supporting document (resume, ID, etc.)', null=True, upload_to='volunteer_documents/'),
        ),
    ]
