# Generated by Django 5.2.8 on 2025-11-20 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_approval_status'),
        ('ministries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_ministry',
            field=models.ForeignKey(blank=True, help_text='Ministry assigned to Priest or Coordinator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_staff', to='ministries.ministry'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='Suspended users cannot log in'),
        ),
    ]
